### ISSUE TITLE
Terraform Provider

### ISSUE THREAD

**Issue by nicholasjackson** [jumppad-labs/jumppad#10]
We are on the fence about whether Shipyard should be a Terraform provider, after much deliveration we felt the workflow was not quite right.

There were things like wanting to be able to do shipyard ssh or having the capability to connect to remote stacks. This did not feel like it fit with the Terraform workflow and follow the Unix principles of a single tool for a single job.

That said, the architecture of the code was set out so that you could import Shipyard as a library and then create a provider from it.

At the moment our feeling is that you turn the Terraform provider on its head a little. We could see shipyard having a Terraform provider which allows you to execute Terraform config as part of the run workflow.

However we are totally open to this, I think the key thing is getting the sweet spot in the workflow, we would be lying if we said we were not heavily influenced by Vagrant and Terraform. We already have the need for a DAG and state, the provider model too should follow Terraform's practices of separate binaries, maybe.

**Comment by ksatirli** [comment]
> which allows you to execute Terraform config as part of the run workflow

A possible option for this is to use `terraform output` and "integrate" that way, rather than having Terraform be executed through Shipyard.

Pro: very little "glue" needed
Con: need to manage Terraform-specific information in Terraform
