### ISSUE TITLE
Port stanza has undocumented required field `remote`

### ISSUE THREAD

**Issue by apollo13** [jumppad-labs/jumppad#238]
**Describe the bug**
The `port` stanza in the `container` and `nomad_cluster` resource has a required property named `remote`:

```
  port {
    local  = 8500
    remote = 8500
    host   = 5800
  }
```

Without it I get this error: `Missing required argument; The argument "remote" is required, but no definition was found.`. But looking at the code I don't think `remote` is ever used (and the docs don't mention it either).

**To Reproduce**
Try running:
```
resource "network" "hashistack" {
  subnet = "10.10.0.0/16"
}
resource "nomad_cluster" "dev" {

  client_nodes=3

  network {
    id = resource.network.hashistack.id
  }

  port {
    local = 1000
    host = 1000
  }
}

output "NOMAD_ADDR" {
  value = "http://${resource.nomad_cluster.dev.external_ip}:${resource.nomad_cluster.dev.api_port}"
}
```
**Expected behavior**
No error

**Comment by nicholasjackson** [comment]
I think I will get rid of remote, it is only there because it exists in the API, but, I don't think I have ever used it. Removing remote will make this much simpler and make things closer to the docker command.

**Comment by eveld** [comment]
Remote was made optional and is not used anymore. It can then later be removed entirely.
